### ISSUE TITLE
Collect more information

### ISSUE THREAD

**Issue by tuanjnfor** [gabriel96x1/ReadE-DocOnline#1] opened 2023-12-20 16:52 UTC
Dear Mr.Gabriel,
Can you help to guide to collect more information from electronic document that is ICAO compliant?
Such as Address...
Thank you so much.
Have a good day!

**Comment by gabriel96x1** [comment] 2023-12-20 19:40
Of course, just be aware that not all the documents have filled all the fields due to some of them are optionals, on the following link you can see which ones are those files:

https://www.icao.int/publications/documents/9303_p10_cons_en.pdf

**Comment by gabriel96x1** [comment] 2023-12-20 19:45
On the following days I'm gonna add these characteristics to the codebase but if you want to add it manually you need to read DG11 file with this code snippet at NFCReadingProcess.kt:

```
 val dg11In = service.getInputStream(PassportService.EF_DG11)
        dg11File = DG11File(dg11In)
```

Then display the read info

**Comment by tuanjnfor** [comment] 2023-12-21 16:42
> On the following days I'm gonna add these characteristics to the codebase but if you want to add it manually you need to read DG11 file with this code snippet at NFCReadingProcess.kt:
> 
> ```
>  val dg11In = service.getInputStream(PassportService.EF_DG11)
>         dg11File = DG11File(dg11In)
> ```
> 
> Then display the read info

Yes, I already try with it.

 val dg11In = service.getInputStream(PassportService.EF_DG11)
        dg11File = DG11File(dg11In)
        
But I got error message: 

2023-12-21 23:37:41.906 25976-26059 ReadingNFC              com.mutablestate.readonline          E  File not found, CAPDU = 00A4020C02010B, RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)

Same problem with DG12File, DG14File, DG15File
I don't now what is problem in here.
Please let me know your result when you try with it.
Thank you so much!

**Comment by gabriel96x1** [comment] 2023-12-21 20:30
As response APDU indicate: RAPDU = 6A82 (SW = 0x6A82: FILE NOT FOUND)

These files are not present on the applet of your eDoc, this is due to only  DG1 and DG2 are mandatory, the rest of them are either optionals or conditionals as the standard indicates, include them or not when the document is personalized rely completely on the issuer, then you can try the following code to just handle the error and only obtain the information from the files you have on your doc:

```
        try {
            dg11File = DG11File(dg11In)
        } catch (e: Exception) {
            dg11File = null
            Log.d(this.TAG, e.message.toString())
        }
```

This means that these optional or conditional variables should be nullable,

I'm not able to reproduce the issue on my side due to the documents I have contains those files, so kindly try this code.

**Comment by gabriel96x1** [comment] 2024-01-05 17:43
Closing due to no more replies

**Closed as completed by gabriel96x1** 2024-01-05 17:43 UTC
